server:
  port: 8088
  tomcat:
    basedir: d://tmp/tomcat
spring:
  application:
    name: client1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/  #服务注册
  instance:
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    # 配置说明 # lease-renewal-interval-in-seconds 每间隔10s，向服务端发送一次心跳，证明自己依然“存活”
    # lease-expiration-duration-in-seconds 告诉服务端，如果我20s之内没有给你发心跳，就代表 我“死”了，将我踢出掉。
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
ribbon:
  eureka:
    enabled: true
#hadoop
hdfs_path: hdfs://192.168.138.135:9000
realPath: /uploadFiles
dirPath: /test



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luoyl.eureka_client.entity
#mybatis日志打印sql
#mapper接口位置: 日志级别
logging:
  level:
    com.luoyl.eureka_client.dao: debug


